services:
  - type: web
    name: coal-erp-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: '4000'
